---
title: "House price prediction"
output: pdf_document
date: "2023-05-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Required Packages

```{r}
library(tidyverse)
library(tinytex)
library(psych)
library(haven)

```

# Import the data set

```{r}
housing <- read_csv("../data/Housing.csv")
head(housing)

```

# Remove null values

```{r}
house_price <- na.omit(housing)
head(house_price)
```

# Summary

```{r}
summary(house_price)
```

# Structure of the data set

```{r}
str(house_price)
```

# Kaiser-Meyer-Olkin factor adequeacy

```{r}
KMO(house_price)
```

```{r}
cortest.bartlett(house_price)
```

# Correlation matrix

```{r}
cor(house_price)
```

# Principle Component Analysis

```{r}
pca(house_price, nfactors = 3, rotate = F)
```

```{r}
fcal <- pca(house_price, nfactors = 3, rotate = F)
fcal
print(fcal$loadings, cutoff = 0.5)
```

```{r}
fcal$communality
```

```{r}
fana <- pca(house_price, nfactors = 3, rotate = "varimax")
fana

print(fana$loadings, cutoff = 0.5)
```

```{r}
pcom <- princomp(house_price, scores = TRUE, cor = TRUE)
pcom
```

```{r}
plot(pcom, col = c(4), main = "Principle component")
```

```{r}
screeplot(pcom, type = "line", main = "Scree plot for Factors", col = c(2))
```
